# Generated by Django 4.1.4 on 2022-12-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_mobile_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='img_url',
            field=models.TextField(default='no img'),
        ),
    ]
